#!/bin/bash
#
# dev-compose.sh — Module management for MikoPBX development containers
#
# Replaces manual docker-compose -f flag management with a declarative
# modules.yml config and auto-generated docker-compose overlay.
#
# This script lives in ExtensionsDevTools_new/docker/ but operates
# from ../../dev_docker/ where docker-compose files and container
# data reside. Creates dev_docker/ on first run if absent.
#
# Usage:
#   ./dev-compose.sh up                       # generate overlay + start container
#   ./dev-compose.sh down                     # stop container
#   ./dev-compose.sh restart                  # down + clear logs + up
#   ./dev-compose.sh enable  ModulePhoneBook  # enable module + restart
#   ./dev-compose.sh disable ModuleLdapSync   # disable module + restart
#   ./dev-compose.sh migrate                  # run module DB migrations
#   ./dev-compose.sh status                   # show container + enabled modules
#   ./dev-compose.sh list                     # list all modules with status
#   ./dev-compose.sh generate                 # regenerate overlay only
#   ./dev-compose.sh ssh                      # open shell in container
#

set -euo pipefail

# --- Path Resolution ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK_DIR="${DEV_DOCKER_DIR:-$SCRIPT_DIR/../../dev_docker}"

# Create work directory if absent
if [[ ! -d "$WORK_DIR" ]]; then
    echo "Creating $WORK_DIR ..."
    mkdir -p "$WORK_DIR"
fi

WORK_DIR="$(cd "$WORK_DIR" && pwd)"
cd "$WORK_DIR"

# Configuration
BASE_FILE="${DEV_COMPOSE_BASE:-docker-compose-modules-api-refactoring.yml}"
MODULES_FILE="modules.yml"
GENERATED_FILE=".generated-docker-compose-modules.yml"
CONTAINER_NAME="mikopbx_modules-api-refactoring"
SERVICE_NAME="mikopbx-modules-api-refactoring"
LOG_DIR="tmp/projects/modules-api-refactoring/storage/usbdisk1/mikopbx/log"

# Copy default modules.yml from template on first run
if [[ ! -f "$MODULES_FILE" && -f "$SCRIPT_DIR/modules.yml.example" ]]; then
    cp "$SCRIPT_DIR/modules.yml.example" "$MODULES_FILE"
    echo "Created $WORK_DIR/$MODULES_FILE from template"
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# --- YAML Parsing (bash 3 compatible — no associative arrays) ---
# Parallel indexed arrays: module_ids[], module_paths[], module_flags[]
module_ids=()
module_paths=()
module_flags=()

parse_modules() {
    if [[ ! -f "$MODULES_FILE" ]]; then
        echo -e "${RED}Error: $MODULES_FILE not found in $WORK_DIR${NC}" >&2
        echo "Copy the template: cp $SCRIPT_DIR/modules.yml.example $WORK_DIR/$MODULES_FILE"
        exit 1
    fi

    module_ids=()
    module_paths=()
    module_flags=()

    local current_module=""
    local current_idx=-1
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// /}" ]] && continue

        # Module ID line: exactly 2 spaces indent, word ending with colon
        if [[ "$line" =~ ^[[:space:]]{2}([A-Za-z][A-Za-z0-9_]+):$ ]]; then
            current_module="${BASH_REMATCH[1]}"
            module_ids+=("$current_module")
            module_paths+=("../Extensions/$current_module")
            module_flags+=("false")
            current_idx=$(( ${#module_ids[@]} - 1 ))
            continue
        fi

        # path: value (4+ spaces indent)
        if [[ -n "$current_module" && "$line" =~ ^[[:space:]]+path:[[:space:]]*(.+)$ ]]; then
            local val="${BASH_REMATCH[1]}"
            # Trim trailing whitespace
            val="${val%"${val##*[![:space:]]}"}"
            module_paths[$current_idx]="$val"
            continue
        fi

        # enabled: value (4+ spaces indent)
        if [[ -n "$current_module" && "$line" =~ ^[[:space:]]+enabled:[[:space:]]*(true|false) ]]; then
            module_flags[$current_idx]="${BASH_REMATCH[1]}"
            continue
        fi
    done < "$MODULES_FILE"
}

# --- Overlay Generation ---

generate_overlay() {
    parse_modules

    local has_enabled=false
    local i
    for i in "${!module_flags[@]}"; do
        if [[ "${module_flags[$i]}" == "true" ]]; then
            has_enabled=true
            break
        fi
    done

    cat > "$GENERATED_FILE" << HEADER
# AUTO-GENERATED by dev-compose.sh — do not edit manually
# Regenerate with: $SCRIPT_DIR/dev-compose.sh generate
services:
  ${SERVICE_NAME}:
    volumes:
HEADER

    if ! $has_enabled; then
        echo "      []" >> "$GENERATED_FILE"
        echo -e "${YELLOW}Warning: No modules enabled${NC}"
        return
    fi

    # Sort module IDs for deterministic output
    local sorted_indices
    sorted_indices=$(
        for i in "${!module_ids[@]}"; do
            echo "$i ${module_ids[$i]}"
        done | sort -k2 | awk '{print $1}'
    )

    for i in $sorted_indices; do
        [[ "${module_flags[$i]}" != "true" ]] && continue

        local module_id="${module_ids[$i]}"
        local path="${module_paths[$i]}"
        local base="/storage/usbdisk1/mikopbx/custom_modules/$module_id"

        if [[ ! -d "$path" ]]; then
            echo -e "${YELLOW}Warning: Module directory not found: $path ($module_id)${NC}" >&2
            continue
        fi

        echo "      # --- $module_id ---" >> "$GENERATED_FILE"

        # Standard directories
        for dir in App Lib Messages Models bin agi-bin Sounds; do
            if [[ -d "$path/$dir" ]]; then
                echo "      - $path/$dir:$base/$dir:ro" >> "$GENERATED_FILE"
            fi
        done

        # Vendor directory
        if [[ -d "$path/vendor" ]]; then
            echo "      - $path/vendor:$base/vendor:ro" >> "$GENERATED_FILE"
        fi

        # Composer files
        if [[ -f "$path/composer.json" ]]; then
            echo "      - $path/composer.json:$base/composer.json:ro" >> "$GENERATED_FILE"
        fi
        if [[ -f "$path/composer.lock" ]]; then
            echo "      - $path/composer.lock:$base/composer.lock:ro" >> "$GENERATED_FILE"
        fi

        # Asset caches
        if [[ -d "$path/public/assets/js" ]]; then
            echo "      - $path/public/assets/js:/var/tmp/www_cache/js/$module_id:ro" >> "$GENERATED_FILE"
        fi
        if [[ -d "$path/public/assets/css" ]]; then
            echo "      - $path/public/assets/css:/var/tmp/www_cache/css/$module_id:ro" >> "$GENERATED_FILE"
        fi

        # Views
        if [[ -d "$path/App/Views" ]]; then
            echo "      - $path/App/Views:/var/tmp/www_cache/view/$module_id:ro" >> "$GENERATED_FILE"
        fi
    done

    echo -e "${GREEN}Generated $WORK_DIR/$GENERATED_FILE${NC}"
}

# --- Docker Compose Wrapper ---

compose_cmd() {
    docker compose -f "$BASE_FILE" -f "$GENERATED_FILE" "$@"
}

# --- Commands ---

cmd_up() {
    generate_overlay
    echo -e "${CYAN}Starting container...${NC}"
    compose_cmd up -d
    echo ""
    cmd_status
}

cmd_down() {
    if [[ ! -f "$GENERATED_FILE" ]]; then
        docker compose -f "$BASE_FILE" down
    else
        compose_cmd down
    fi
    echo -e "${GREEN}Container stopped${NC}"
}

cmd_restart() {
    echo -e "${CYAN}Restarting...${NC}"
    cmd_down 2>/dev/null || true
    if [[ -d "$LOG_DIR" ]]; then
        rm -rf "$LOG_DIR"
        echo -e "${CYAN}Cleared logs${NC}"
    fi
    cmd_up
}

cmd_enable() {
    local target="$1"
    if [[ -z "$target" ]]; then
        echo -e "${RED}Usage: $0 enable <ModuleID>${NC}" >&2
        exit 1
    fi

    if ! grep -q "^  ${target}:" "$MODULES_FILE" 2>/dev/null; then
        echo -e "${RED}Error: Module '$target' not found in $MODULES_FILE${NC}" >&2
        echo "Add it first, then run enable."
        exit 1
    fi

    # Replace enabled: false with enabled: true for the target module
    awk -v mod="$target" '
        /^  [A-Za-z]/ { current = $0; sub(/:$/, "", current); gsub(/^[[:space:]]+/, "", current) }
        current == mod && /enabled:/ { sub(/false/, "true") }
        { print }
    ' "$MODULES_FILE" > "${MODULES_FILE}.tmp" && mv "${MODULES_FILE}.tmp" "$MODULES_FILE"

    echo -e "${GREEN}Enabled $target${NC}"
    cmd_restart
}

cmd_disable() {
    local target="$1"
    if [[ -z "$target" ]]; then
        echo -e "${RED}Usage: $0 disable <ModuleID>${NC}" >&2
        exit 1
    fi

    if ! grep -q "^  ${target}:" "$MODULES_FILE" 2>/dev/null; then
        echo -e "${RED}Error: Module '$target' not found in $MODULES_FILE${NC}" >&2
        exit 1
    fi

    # Replace enabled: true with enabled: false for the target module
    awk -v mod="$target" '
        /^  [A-Za-z]/ { current = $0; sub(/:$/, "", current); gsub(/^[[:space:]]+/, "", current) }
        current == mod && /enabled:/ { sub(/true/, "false") }
        { print }
    ' "$MODULES_FILE" > "${MODULES_FILE}.tmp" && mv "${MODULES_FILE}.tmp" "$MODULES_FILE"

    echo -e "${GREEN}Disabled $target${NC}"
    cmd_restart
}

cmd_migrate() {
    echo -e "${CYAN}Running module DB migrations...${NC}"
    docker exec "$CONTAINER_NAME" php -f /usr/www/src/Core/System/Upgrade/UpdateModulesDatabase.php
}

cmd_status() {
    echo -e "${CYAN}=== Container ===${NC}"
    docker ps --filter "name=$CONTAINER_NAME" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "Container not running"
    echo ""
    echo -e "${CYAN}=== Enabled Modules ===${NC}"
    parse_modules
    local sorted_indices
    sorted_indices=$(
        for i in "${!module_ids[@]}"; do
            echo "$i ${module_ids[$i]}"
        done | sort -k2 | awk '{print $1}'
    )
    for i in $sorted_indices; do
        if [[ "${module_flags[$i]}" == "true" ]]; then
            local path="${module_paths[$i]}"
            local module_id="${module_ids[$i]}"
            if [[ -d "$path" ]]; then
                echo -e "  ${GREEN}✓${NC} $module_id  ${CYAN}($path)${NC}"
            else
                echo -e "  ${RED}✗${NC} $module_id  ${RED}(missing: $path)${NC}"
            fi
        fi
    done
}

cmd_list() {
    parse_modules
    echo -e "${CYAN}=== All Modules ===${NC}"
    local sorted_indices
    sorted_indices=$(
        for i in "${!module_ids[@]}"; do
            echo "$i ${module_ids[$i]}"
        done | sort -k2 | awk '{print $1}'
    )
    for i in $sorted_indices; do
        local module_id="${module_ids[$i]}"
        local status="${module_flags[$i]}"
        local path="${module_paths[$i]}"
        if [[ "$status" == "true" ]]; then
            if [[ -d "$path" ]]; then
                echo -e "  ${GREEN}[on] ${NC} $module_id  ${CYAN}($path)${NC}"
            else
                echo -e "  ${RED}[on!]${NC} $module_id  ${RED}(missing: $path)${NC}"
            fi
        else
            echo -e "  ${YELLOW}[off]${NC} $module_id  ($path)"
        fi
    done
}

cmd_generate() {
    generate_overlay
}

cmd_ssh() {
    docker exec -it "$CONTAINER_NAME" /bin/sh
}

cmd_help() {
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  up                    Generate overlay and start container"
    echo "  down                  Stop container"
    echo "  restart               Stop, clear logs, and start container"
    echo "  enable  <ModuleID>    Enable a module and restart"
    echo "  disable <ModuleID>    Disable a module and restart"
    echo "  migrate               Run module DB migrations in container"
    echo "  status                Show container status and enabled modules"
    echo "  list                  List all modules with enabled/disabled status"
    echo "  generate              Regenerate overlay file only (no restart)"
    echo "  ssh                   Open shell in container"
    echo ""
    echo "Environment variables:"
    echo "  DEV_COMPOSE_BASE      Base docker-compose file (default: $BASE_FILE)"
    echo "  DEV_DOCKER_DIR        Work directory (default: $SCRIPT_DIR/../../dev_docker)"
}

# --- Main ---

case "${1:-help}" in
    up)       cmd_up ;;
    down)     cmd_down ;;
    restart)  cmd_restart ;;
    enable)   cmd_enable "${2:-}" ;;
    disable)  cmd_disable "${2:-}" ;;
    migrate)  cmd_migrate ;;
    status)   cmd_status ;;
    list)     cmd_list ;;
    generate) cmd_generate ;;
    ssh)      cmd_ssh ;;
    help|-h|--help) cmd_help ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}" >&2
        cmd_help
        exit 1
        ;;
esac
